###########
# site.title

title: SPACEKITCAT
subtitle: 'get out of my recreational vehicle, punk'

author:
  name: Lisa A. Burton
  email: spacekitcat+blog@protonmail.com
  github: spacekitcat
  twitter: spacekitcat

plugins:
  - jekyll-gist

nav:
  - { title: 'Projects', href: '/' }

#########################
# more settings

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: css
  style: expanded

exclude:
  - README.md
  - LICENSE.md
